version: 2

updates:
  - directory: /
    package-ecosystem: 'npm'
    schedule:
      interval: 'weekly'
      time: '18:00' # UTC, = ~10AM Pacific
    groups:
      npm-major:
        update-types:
          - major
      npm-minor:
        update-types:
          - minor
          - patch

  - directory: /
    package-ecosystem: 'github-actions'
    schedule:
      interval: 'weekly'
      time: '18:00' # UTC, = ~10AM Pacific
    groups:
      gha-major:
        update-types:
          - major
      gha-minor:
        update-types:
          - minor
          - patch
